# Generated by Django 4.2.2 on 2023-06-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=3000, verbose_name='Описание задачи')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('done', 'Сделано')], default='new', max_length=40, verbose_name='Статус')),
                ('date_of_completion', models.DateField(blank=True, default='null', null=True, verbose_name='Дата выполнения')),
            ],
            options={
                'verbose_name': 'Список задач',
                'verbose_name_plural': 'Список задач',
                'db_table': 'to_do_list',
            },
        ),
    ]
