# Generated by Django 4.2.2 on 2023-06-20 17:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_alter_todolist_date_of_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='name_task',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Название задачи'),
            preserve_default=False,
        ),
    ]
