# Generated by Django 4.2.2 on 2023-06-20 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_todolist_name_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='name_task',
        ),
    ]
