# Generated by Django 4.2.2 on 2023-06-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_remove_todolist_name_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='name_task',
            field=models.CharField(default='none', max_length=100, verbose_name='Название задачи'),
            preserve_default=False,
        ),
    ]
